### ISSUE TITLE
Browser support checklist

### ISSUE THREAD

**Issue by albrow** [0xProject/0x-mesh#66]
This issue serves as a way to track overall progress on WebAssembly/browser compatibility. A lot of progress has already been made. For example, we added WebAssembly support to [pion/webrtc](https://github.com/pion/webrtc/pull/479) which will serve as the underlying mechanism for establishing a direct connection between two browser-based peers.

Here are the remaining tasks (including those already in progress):

- [ ] Reach general consensus on specification for [WebRTC signaling protocol](https://github.com/libp2p/specs/pull/159).
- [ ] Depending on where we land with the signaling protocol, we may need to add Wasm support to [go-ws-transport](https://github.com/libp2p/go-ws-transport). Browser peers would use the WebSocket transport to communicate with a signaler and then switch to the WebRTC transport with the desired peer after signaling is complete.
- [ ] Update [go-libp2p-webrtc-direct](https://github.com/libp2p/go-libp2p-webrtc-direct) to support direct browser-to-browser connections via the signaling protocol, or alternatively, create a new transport that supports them.
- [ ] Add Wasm support to [go-libp2p-peerstore](https://github.com/libp2p/go-libp2p-peerstore).
- [ ] Create Wasm-compataible peer discovery mechanism (likely either [Kademlia DHT](https://github.com/libp2p/go-libp2p-kad-dht) or [Peer Exchange](https://en.wikipedia.org/wiki/Peer_exchange)).
- [ ] Update BrowserFS to [support special file descriptors 0, 1, and 2](https://github.com/jvilk/BrowserFS/issues/271).
- [ ] Add WebAssembly support to [go-leveldb](https://github.com/syndtr/goleveldb), likely by using BrowserFS. [Partial Wasm support](https://github.com/syndtr/goleveldb/pull/277) (works in Node but not in browsers) has already been implemented.
- [ ] Implement JavaScript/TypeScript callback functions for interacting with 0x Mesh from the browser.
- [ ] Publish JavaScript/TypeScript package which is a wrapper around our callback functions and the Wasm bundle.

**Comment by albrow** [comment]
Closing this in favor of individual issues and a Milestone: https://github.com/0xProject/0x-mesh/milestone/2.
